import "./globals.css";
import { inter, montserrat } from "./fonts";
import Header from "./components/Header";
import { Footer } from "./components/Footer";

export const metadata = {
	title: "Pikurate",
	description: "Generated by create next app",
	keywords: "pikurate, nextjs, tailwindcss",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={`${inter.variable} ${montserrat.variable}`}>
			<body className="text-black">
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
