import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Pikurate",
	description: "Generated by create next app",
	keywords: "pikurate, nextjs, tailwindcss",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="text-black">
				<Header />
				{children}
			</body>
		</html>
	);
}
